name: Generate 3D Contribution Profile

on:
  push:
    branches:
      - main  # or the branch you want to track

jobs:
  profile-3d-contrib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Generate 3D GitHub Contributions
        uses: ghprofile/3d-contrib@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: 'Tejasgaik2001'
          theme: 'github-dark'  # Customize the theme (e.g., github-light, github-dark)
